POST http://localhost:8080/save/apple
Content-Type: application/json

{
    "HELLO": 1
}

###
GET http://localhost:8080/retrieve/apple
Accept: application/json

###

GET http://localhost:8080/contains/apple
Accept: application/json

###
