POST http://localhost:8091/save/apple
Content-Type: application/json

{
    "HELLO": 1
}

###
GET http://localhost:8091/retrieve/apple
Accept: application/json

###

GET http://localhost:8091/contains/apple
Accept: application/json

###

POST http://localhost:8091/remove/apple
Accept: application/json

###
