POST https://ihmap_master-generous-hippopotamus-ov.cfapps.us10-001.hana.ondemand.com/save/apple
Content-Type: application/json

{
    "HELLO": 1
}

###
GET https://ihmap_master-generous-hippopotamus-ov.cfapps.us10-001.hana.ondemand.com/retrieve/apple
Accept: application/json

###

GET https://ihmap_master-generous-hippopotamus-ov.cfapps.us10-001.hana.ondemand.com/contains/apple
Accept: application/json

###
