version: '3'
services:
    master:
        image: python:3
        container_name: masternode
        environment:
            PYTHONUNBUFFERED: 1
            PYTHONPATH: "/home/app"
            DATA_HOST: ""
            CACHE_CONFIG: >
                {
                    "NO_OF_NODES" : 1
                }
        ports:
            - "8080:8000"
        working_dir: /home/app/masternode
        entrypoint: sh start.sh
        volumes:
            - ./masternode:/home/app/masternode